services:
  controle-producao:
    image: ghcr.io/prudenciooficial/controle-de-producao:latest
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    volumes:
      # Manter logs se necessário
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app-data: 