// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://cvctmbxotzxdzjvokdjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Y3RtYnhvdHp4ZHpqdm9rZGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDIyNDUsImV4cCI6MjA2MjIxODI0NX0.PaBOri64cpaDnCTu-96U1plfw78Q_y_RYiqE1BJ66uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
